' AddBOM — add a new BOM (Components) tab by cloning the hidden
' template sheet, add its per-tab volume column to Volumes, and add
' its per-group totals row to Overview.
'
' The template is a veryHidden sheet (named _BOMTemplate) generated by
' the TypeScript writer (src/xlsx/bom.ts) for macro-enabled workbooks,
' so it cannot be renamed or deleted from the Excel UI.
'
' Sheet layouts (see src/xlsx/vol.ts and src/xlsx/overview.ts):
'   Volumes
'     - row 1 carries the "Tab Volumes" title at the per-tab block's
'       first column
'     - the header row (title row + 2) holds one cell per BOM tab
'     - each tier group row has a SUMIFS cell per tab
'     - the group row's "Tiered Volume" SUM spans one column past the
'       last tab, so inserting a column there auto-expands the sums
'   Overview
'     - per-group rows: B = group label, M = group key, D..I = yearly
'       formulas, N..T = per-tab SUMIFS (set-up + years)
'     - the "total tabs" row (M column) holds SUMs over every tab's
'       TOTAL_SETUP / TOTAL_MONTHLY (found via the "Set-up:" /
'       "Monthly Total:" labels on each BOM tab)
'     - the footer row ("Totals" in column B) closes the group block;
'       inserting a row there auto-expands its SUM ranges and shifts
'       all downstream references (ESA section)

Private Const TEMPLATE_NAME = "_BOMTemplate"

' Group that the cloned template contains (mirrors TEMPLATE_SECTION_QTY
' and TEMPLATE_SECTION_FUNCTION in src/xlsx/constants.ts)
Private Const NEW_GROUP_KEY = "gen"
Private Const NEW_GROUP_LABEL = "General"

Sub AddBOM()
  Dim ws As Worksheet
  Dim srcTab As String
  Set ws = CloneBOMTab()
  If ws Is Nothing Then Exit Sub
  srcTab = AddVolumesColumn(ws.Name)
  If srcTab <> "" Then
    AddOverviewRow ws.Name, srcTab, NEW_GROUP_KEY, NEW_GROUP_LABEL
  End If
End Sub

' Clone the hidden template as the next free ComponentsN tab.
Private Function CloneBOMTab() As Worksheet
  Dim tmpl As Worksheet
  Dim ws As Worksheet
  Dim n As Long

  On Error Resume Next
  Set tmpl = ThisWorkbook.Worksheets(TEMPLATE_NAME)
  On Error GoTo 0
  If tmpl Is Nothing Then
    MsgBox "Template sheet '" & TEMPLATE_NAME & "' is missing.", vbExclamation
    Exit Function
  End If

  ' Pick the lowest free number: Components1, Components2, ...
  n = 1
  Do While SheetExists("Components" & n)
    n = n + 1
  Loop

  tmpl.Visible = xlSheetVisible
  ' Insert before the template so new tabs land at the END of the
  ' component-tab group (the template stays last among them)
  tmpl.Copy Before:=tmpl
  tmpl.Visible = xlSheetVeryHidden
  Set ws = ActiveSheet
  ws.Name = "Components" & n
  ws.Activate
  Set CloneBOMTab = ws
End Function

' Add a per-tab volume column for tabName at the end of the
' "Tab Volumes" block on the Volumes sheet.
' Returns the name of the tab the column pattern was copied from.
Private Function AddVolumesColumn(tabName As String) As String
  Dim ws As Worksheet
  Dim hdrRow As Long
  Dim firstCol As Long
  Dim srcCol As Long
  Dim newCol As Long
  Dim lastRow As Long
  Dim r As Long
  Dim srcName As String
  Dim f As String

  On Error Resume Next
  Set ws = ThisWorkbook.Worksheets("Volumes")
  On Error GoTo 0
  If ws Is Nothing Then Exit Function

  firstCol = FindInRow(ws.Rows(1), "Tab Volumes")   ' anchor: block start
  If firstCol = 0 Then Exit Function
  hdrRow = 1 + 2

  ' Last per-tab header cell = source column to copy from
  srcCol = firstCol
  Do While ws.Cells(hdrRow, srcCol + 1).Value <> ""
    srcCol = srcCol + 1
  Loop
  srcName = ws.Cells(hdrRow, srcCol).Value
  newCol = srcCol + 1

  ' Insert at the SUM ranges' right edge -> they auto-expand
  ws.Columns(newCol).Insert Shift:=xlToRight
  Application.CutCopyMode = False

  ' Header cell: copy format + width, then the new name
  ws.Cells(hdrRow, srcCol).Copy Destination:=ws.Cells(hdrRow, newCol)
  ws.Cells(hdrRow, newCol).Value = tabName
  ws.Columns(newCol).ColumnWidth = ws.Columns(srcCol).ColumnWidth

  ' Per-tab formulas on each tier group row: copy + substitute tab name
  lastRow = ws.Cells(ws.Rows.Count, srcCol).End(xlUp).Row
  For r = hdrRow + 1 To lastRow
    If ws.Cells(r, srcCol).HasFormula Then
      f = SwapSheetName(ws.Cells(r, srcCol).Formula, srcName, tabName)
      ws.Cells(r, srcCol).Copy Destination:=ws.Cells(r, newCol)
      ws.Cells(r, newCol).Formula = f
    End If
  Next r
  Application.CutCopyMode = False
  AddVolumesColumn = srcName
End Function

' Add the new tab's per-group totals row to the Overview sheet and
' extend the "total tabs" SUMs with the new tab's overall totals.
Private Sub AddOverviewRow(tabName As String, srcTab As String, _
                           groupKey As String, groupLabel As String)
  Dim ws As Worksheet
  Dim newTab As Worksheet
  Dim footerRow As Long
  Dim blockTop As Long
  Dim srcRow As Long
  Dim newRow As Long
  Dim totalsRow As Long
  Dim c As Long
  Dim f As String
  Dim tabRef As String
  Dim setupCell As String
  Dim monthlyCell As String
  Dim patTab As String

  On Error Resume Next
  Set ws = ThisWorkbook.Worksheets("Overview")
  On Error GoTo 0
  If ws Is Nothing Then Exit Sub

  footerRow = FindInColumn(ws, "B", "Totals")
  If footerRow = 0 Then Exit Sub
  blockTop = FindInColumn(ws, "B", "Per-Group Prices")
  If blockTop = 0 Then Exit Sub
  blockTop = blockTop + 2              ' first group row

  ' Always insert a fresh row: at the topmost gap in the group block if
  ' there is one, otherwise just above the footer.  Existing (empty)
  ' rows are left untouched.
  newRow = FindEmptyGroupRow(ws, blockTop, footerRow)
  If newRow = 0 Then
    newRow = footerRow
    srcRow = footerRow - 1            ' last group row = pattern
  Else
    srcRow = FindFirstGroupRow(ws, blockTop, footerRow)
    If srcRow = 0 Then Exit Sub
    If srcRow >= newRow Then srcRow = srcRow + 1   ' shifts with the insert
  End If

  ws.Rows(newRow).Insert Shift:=xlDown
  Application.CutCopyMode = False

  ' Copy the pattern row (formulas + formats), then rewrite labels
  ws.Range(ws.Cells(srcRow, 1), ws.Cells(srcRow, 20)).Copy _
      Destination:=ws.Cells(newRow, 1)
  Application.CutCopyMode = False
  ws.Cells(newRow, 2).Value = groupLabel      ' B: group label
  ws.Cells(newRow, 13).Value = groupKey       ' M: group key

  ' The pattern row's formulas reference their own tab; derive it from
  ' the copied SUMIFS rather than assuming it is srcTab.
  patTab = SheetNameInFormula(ws.Cells(newRow, 14).Formula)
  If patTab = "" Then patTab = srcTab

  ' Point every formula in the new row at the new tab
  For c = 4 To 20
    If ws.Cells(newRow, c).HasFormula Then
      f = SwapSheetName(ws.Cells(newRow, c).Formula, patTab, tabName)
      ws.Cells(newRow, c).Formula = f
    End If
  Next c

  ' Extend the overall totals: "total tabs" row, N and O columns
  totalsRow = FindInColumn(ws, "M", "total tabs")
  If totalsRow = 0 Then Exit Sub
  Set newTab = ThisWorkbook.Worksheets(tabName)
  tabRef = SheetRefName(tabName)
  setupCell = FindLabelCell(newTab, "Set-up:")
  monthlyCell = FindLabelCell(newTab, "Monthly Total:")

  If setupCell <> "" Then
    f = ws.Cells(totalsRow, 14).Formula      ' N: sum of TOTAL_SETUP
    f = Left(f, Len(f) - 1) & "," & tabRef & "!" & setupCell & ")"
    ws.Cells(totalsRow, 14).Formula = f
  End If
  If monthlyCell <> "" Then
    f = ws.Cells(totalsRow, 15).Formula      ' O: sum of TOTAL_MONTHLY
    f = Left(f, Len(f) - 1) & "," & tabRef & "!" & monthlyCell & ")"
    ws.Cells(totalsRow, 15).Formula = f
  End If
End Sub

' Rewrite sheet references in a formula from src to dst (quoted and
' unquoted forms).
Private Function SwapSheetName(f As String, src As String, dst As String) As String
  Dim srcQ As String
  Dim dstQ As String
  srcQ = Replace(src, "'", "''")
  dstQ = Replace(dst, "'", "''")
  f = Replace(f, "'" & srcQ & "'!", "'" & dstQ & "'!")
  SwapSheetName = Replace(f, src & "!", dst & "!")
End Function

' Quoted sheet reference (always quoted; valid even when not required).
Private Function SheetRefName(n As String) As String
  SheetRefName = "'" & Replace(n, "'", "''") & "'"
End Function

' Absolute reference ($E$2 style) of the cell right of the given label
' in column D of a BOM sheet (e.g. "Set-up:", "Monthly Total:").
Private Function FindLabelCell(ws As Worksheet, label As String) As String
  Dim r As Long
  FindLabelCell = ""
  For r = 1 To 10
    If ws.Cells(r, "D").Value = label Then
      FindLabelCell = ws.Cells(r, "E").Address(True, True)
      Exit Function
    End If
  Next r
End Function

' Row of the first cell in a column whose value matches.
Private Function FindInColumn(ws As Worksheet, col As String, what As String) As Long
  Dim r As Long
  FindInColumn = 0
  For r = 1 To 200
    If ws.Cells(r, col).Value = what Then
      FindInColumn = r
      Exit Function
    End If
  Next r
End Function

' Topmost row in the group block (topRow..footerRow-1) with neither a
' group label (B) nor a group key (M); 0 if the block is full.
Private Function FindEmptyGroupRow(ws As Worksheet, topRow As Long, bottomRow As Long) As Long
  Dim r As Long
  FindEmptyGroupRow = 0
  For r = topRow To bottomRow - 1
    If ws.Cells(r, 2).Value = "" And ws.Cells(r, 13).Value = "" Then
      FindEmptyGroupRow = r
      Exit Function
    End If
  Next r
End Function

' First row in the group block that has a label or key (pattern row).
Private Function FindFirstGroupRow(ws As Worksheet, topRow As Long, bottomRow As Long) As Long
  Dim r As Long
  FindFirstGroupRow = 0
  For r = topRow To bottomRow - 1
    If ws.Cells(r, 2).Value <> "" Or ws.Cells(r, 13).Value <> "" Then
      FindFirstGroupRow = r
      Exit Function
    End If
  Next r
End Function

' Sheet name of the first sheet reference (X! or 'X'!) in a formula.
Private Function SheetNameInFormula(f As String) As String
  Dim p As Long
  Dim s As Long
  Dim raw As String
  p = InStr(f, "!")
  If p = 0 Then Exit Function
  s = p - 1
  Do While s > 0
    If Not Mid(f, s, 1) Like "[A-Za-z0-9_.' ]" Then Exit Do
    s = s - 1
  Loop
  raw = Trim(Mid(f, s + 1, p - s - 1))
  If Left(raw, 1) = "'" And Right(raw, 1) = "'" Then
    raw = Mid(raw, 2, Len(raw) - 2)
    raw = Replace(raw, "''", "'")
  End If
  SheetNameInFormula = raw
End Function

' Column of the first cell in a row whose value matches.
Private Function FindInRow(rng As Range, what As String) As Long
  Dim c As Range
  FindInRow = 0
  For Each c In rng.Cells
    If c.Value = what Then
      FindInRow = c.Column
      Exit Function
    End If
  Next c
End Function

Private Function SheetExists(sheetName As String) As Boolean
  Dim ws As Worksheet
  On Error Resume Next
  Set ws = ThisWorkbook.Worksheets(sheetName)
  On Error GoTo 0
  SheetExists = Not ws Is Nothing
End Function
